language: cpp
sudo: required
dist: trusty

before_install:
- sudo apt-get update
- sudo apt-get install xorg-dev libglu1-mesa-dev

compiler:
- gcc

script:
- mkdir build
- cd build
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ..
- cmake --build .

notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7